context:
  - label:
      eng: 1 paragraph
      swe: 1 paragraph
    value: 1 paragraph
description:
  swe: Semper Barbarus
  eng: Semper and Barbarus
id: semperbarbarus
mode:
  - name: litterary

pos_attributes:
  - baseform: lemma
  - pos: epos
  - number: number
  - cases: case
  - voice: voice
  - tense: tense
  - nominal: nominal
  - mood: mood
  - person: person
  - negation: negation

struct_attributes:
  - sender: sender
  - recipient: recipient
  - place: place
  - year: year

title:
  swe: 'Semper-Barbarus'
  eng: 'Semper-Barbarus'
  est: 'Semperi ja Barbaruse kirjavahetus'
within:
  - label:
      eng: sentence
      swe: mening
    value: sentence
