dataset:
  _A_: A
  _B_: B
  _C_: C
  _D_: D
  _G_: G
  _H_: H
  _I_: I
  _J_: J
  _K_: K
  _N_: N
  _O_: O
  _P_: P
  _Q_: Q
  _S_: S
  _U_: U
  _V_: V
  _X_: X
  _Y_: Y
  _Z_: Z

escape: false
extended_component: datasetSelect
label:
  eng: part-of-speech
  swe: ordklass
  est: sõnaliik
opts:
  is: '='
  is_not: '!='
order: 0
translation:
  _A_:
    eng: adjective
    swe: adjektiv
    est: omadussõna algvõrre
  _B_:
    eng: sentence particle
    swe: partikel
    est: lausepartikkel
  _C_:
    eng: adjective comparative
    swe: adjektiv
    est: omadussõna keskvõrre
  _D_:
    eng: adverb
    swe: adverb
    est: määrsõna
  _G_:
    eng: genitive attribute
    swe: genitive
    est: genitiivatribuut
  _H_:
    eng: proper noun
    swe: egennamn
    est: pärisnimi
  _I_:
    eng: interjection
    swe: interjektion
    est: hüüdsõna
  _K_:
    eng: adposition
    swe: adposition
    est: kaassõna
  _N_:
    eng: cardinal number
    swe: grundtal
    est: põhiarvsõna
  _O_:
    eng: ordinal number
    swe: ordningstal
    est: järgarvsõna
  _P_:
    eng: pronoun
    swe: pronomen
    est: asesõna
  _Q_:
    eng: foreign word
    swe: utländskt ord
    est: tundmatu
  _S_:
    eng: noun
    swe: substantiv
    est: nimisõna
  _U_:
    eng: adjective superlative
    swe: adjective
    est: omadussõna ülivõrre
  _V_:
    eng: verb
    swe: verb
    est: tegusõna
  _X_:
    eng: particle
    swe: partikel
    est: verbi juurde kuuluv sõna
  _Z_:
    eng: punctuation
    swe: interpunktion
    est: kirjavahemärk
